version: '3'

#criar fila no rabbitmq
#ligar a exchange amq.direct a fila, inserir a fila no binding da exchange

services:
  rabbitmq:
    image: 'rabbitmq:3.8.16-management'
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/